version: '3.8'

services:
  web:
    container_name: pms-web
    image: pms-web
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pms-web.rule=Host(`pms.huaquai.cn`)"
      - "traefik.http.routers.pms-web.entrypoints=webSecure"
      - "traefik.http.routers.pms-web.tls=true"
      - "traefik.http.routers.pms-web.tls.certresolver=resolver"
      - "traefik.http.services.pms-web.loadbalancer.server.port=80"
      - "traefik.http.routers.pms-web-http.rule=Host(`pms.huaquai.cn`)"
      - "traefik.http.routers.pms-web-http.entrypoints=web"
      - "traefik.http.routers.pms-web-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  traefik_default:
    external: true